version: '3'

services:
  laravel-react-web:
    image: nginx:stable-alpine
    ports:
      - "33333:80"
    volumes:
      - ./src:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-react-app
    environment:
      VIRTUAL_HOST: localhost:33333

  laravel-react-app:
    image: laravel-react-app
    build: ./docker/php
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www:cached

  laravel-react-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
